version: "3"

services:
  data-dump-service:
    container_name: data-dump
    image: jaypeng2015/show-me-the-money
    restart: always
    ports:
      - 3005:3000
    networks:
      - app-network

  code-drills-backend-service:
    container_name: backend-service
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env.docker
    depends_on:
      - data-dump-service
    ports:
      - 3001:3001
    networks:
      - app-network

  code-drills-frontend-service:
    container_name: frontend-service
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env.docker
    depends_on:
      - code-drills-backend-service
    ports:
      - 3000:3000

networks:
  app-network:
    driver: bridge
